version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    container_name: apache-web-server
    restart: unless-stopped

volumes:
  app-data:
